name: 'My Composite Action'
description: 'A reusable composite action to perform setup and run a script'
inputs:
  example-input:
    description: 'An example input parameter'
    required: true
    default: 'default-value'
  ollama-model-name:
    description: 'Ollama model name'
    required: true
    default: 'llama3.2:latest'
outputs:
  example-output:
    description: 'An example output'
    value: ${{ steps.example-step.outputs.result }}
  installed-ollama-models:
    description: 'List of installed Ollama models'
    value: ${{ steps.list-ollama-models.outputs.models }}
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Run a custom script
      id: example-step
      run: echo "result=Hello from composite action!" >> $GITHUB_OUTPUT
      shell: bash
    - name: Run custom script from file
      run: ${{ github.action_path }}/scripts/my-script.sh ${{ inputs.example-input }}
      shell: bash
    - name: Install Ollama
      shell: bash
      run: |
        if ! command -v ollama > /dev/null 2>&1; then
          curl -fsSL https://ollama.com/install.sh | sh
        fi
    - name: Pull Ollama model
      shell: bash
      run: ollama pull ${{ inputs.ollama-model-name }}
    - name: List installed Ollama models
      id: list-ollama-models
      shell: bash
      run: |
        # Extract only the model names and join into a single line
        echo "models=$(ollama list | awk 'NR>1 {print $1}' | tr '\n' ',')" >> $GITHUB_OUTPUT