name: Test Composite Action
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run my composite action
        uses: ./
        with:
          example-input: 'Test Value'
      - name: Use output
        run: echo "Output was ${{ steps.my-composite-action.outputs.example-output }}"
      - name: Run AI Code Review Action
        id: ai-review
        uses: LiteObject/ai-code-review-action@latest
        with:
          ollama-model-name: "llama3.2:latest"
      - name: Display installed models
        run: echo "Installed models: ${{ steps.ai-review.outputs.installed-ollama-models }}"